// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** UUID for table */
export type Id = string;

/** Represents the table public.users */
export default interface DBUsers {
  /** Database type: pg_catalog.uuid */
  id: Id;

  /** Database type: pg_catalog.timestamptz */
  updated_at: Date;

  /** Database type: pg_catalog.text */
  name: string;

  /** Database type: pg_catalog.text */
  family_name: string;

  /** Database type: pg_catalog.text */
  given_name: string;

  /**
   * Database type: pg_catalog.text
   * The email the user did sign in with. E.g. for google identity_provider it is a gmail email. Cant be changed. If user wants to change, rather has to delete the account.
   */
  email: string;
}

/** Represents the type for inserting entries for the table public.users */
export interface DBUsersInsert {
  /**
   * Database type: pg_catalog.uuid
   * Default value: uuid_generate_v4()
   */
  id?: Id;

  /**
   * Database type: pg_catalog.timestamptz
   * Default value: now()
   */
  updated_at?: Date;

  /** Database type: pg_catalog.text */
  name: string;

  /** Database type: pg_catalog.text */
  family_name: string;

  /** Database type: pg_catalog.text */
  given_name: string;

  /**
   * Database type: pg_catalog.text
   * The email the user did sign in with. E.g. for google identity_provider it is a gmail email. Cant be changed. If user wants to change, rather has to delete the account.
   */
  email: string;
}

/** Represents the type for updating entries for the table public.users */
export interface DBUsersUpdate {
  /** Database type: pg_catalog.uuid */
  id?: Id;

  /** Database type: pg_catalog.timestamptz */
  updated_at?: Date;

  /** Database type: pg_catalog.text */
  name?: string;

  /** Database type: pg_catalog.text */
  family_name?: string;

  /** Database type: pg_catalog.text */
  given_name?: string;

  /**
   * Database type: pg_catalog.text
   * The email the user did sign in with. E.g. for google identity_provider it is a gmail email. Cant be changed. If user wants to change, rather has to delete the account.
   */
  email?: string;
}
